<?php
return array (
    'shop' => '',
    'status' => '',
    'classify' => '',
    'category' => '',
    'sex' => ' ',
    'date_of_birth' => '',
    'area' => '',
    'join_date' => '',
    'promote' => '',
    'source' => '',
    'arrival_time' => '',



    'data_tom' => '',
    'shops' => '',
    'status_tom' => '',
    'source_tom' => '',
    'payment_method' => '',
    'new_yorker' => '',





    'report' => '',
    'stores' => '',
    'date' => '',
    'week' => '',
    'beautician' => '',
    'consultant' => '',
    'member' => '',




    'title' => 'AdaptiveSuite',
    'sitename' => 'Adaptive',
    'keywords' => 'keywords',
    'description' => 'description',
    'footer' => '&copy;2019 Adaptive',
    'from_name' => 'Hygge Spa',
    'site' => '銅鑼灣渣甸街50號渣甸中心18樓全層18/F，Jardine Center No.50 Jardine Bazaar,Causeway Bay,HK',
    'phone' => '97598165',
    'fax' => '',
    'e_mail' => 'cs@hygge.hk',
    'url' => '',



    'employee_data' => 'SF',
    'employee_data_code' => '001',
    'level_and_authority' => 'L',
    'level_and_authority_code' => '01',
    'membership' => 'HS',
    'membership_code' => '0001',
    'supplier_information' => 'V',
    'supplier_information_code' => '001',
    'service_packages' => 'SP-',
    'service_packages_code' => '0001',
    'product' => 'PDU-',
    'product_code' => '0001',
    'product_mix' => 'B',
    'product_mix_code' => '0001',
    'serve' => '',
    'serve_code' => 'AdaptiveSuite',
    'store' => '',
    'reservation' => 'BK',
    'reservation_code' => '000001',
    'invoice' => 'HS',
    'invoice_code' => '000001',
    'package_staging' => 'IS',
    'package_staging_code' => '000001',
    'use_package' => 'U',
    'use_package_code' => '000001',
    'package_refund' => 'RF',
    'package_refund_code' => '000001',
    'ikura' => 'SI',
    'ikura_code' => '000001',
    'dekura' => 'SO',
    'dekura_code' => '000001',
    'turnover' => 'ST',
    'turnover_code' => '000001',
    'expenditure' => 'E',
    'expenditure_code' => '000001',

    'employee_data_code1' => 'SF',
    'employee_data_code2' => 'SF',
    'employee_data_code3' => 'SF',
    'employee_data_code4' => 'SF',
    'employee_data_code5' => 'SF',
    'employee_data_code6' => 'SF',
    'employee_data_code7' => 'SF',
    'employee_data_code8' => 'SF',
    'employee_data_code9' => 'SF',
    'employee_data_code10' => 'SF',
    'employee_data_code11' => 'SF',
    'employee_data_code12' => 'SF',
    'employee_data_code13' => 'SF',
    'employee_data_code14' => 'SF',
    'employee_data_code15' => 'SF',
    'employee_data_code16' => 'SF',
    'employee_data_code17' => 'SF',
    'employee_data_code18' => 'SF',
    'employee_data_code19' => 'SF',
    'employee_data_code20' => 'SF',
    'employee_data_code21' => 'SF',

    'limit_days' => '0',
    'member_no' => '0',
    'content1' => '                            ',
    'content2' => '1111111111        1111111            ',
    'content3' => '                            ',
    'system_idle_time' => '',
    'print_language' => '0',
    'report_language' => '0',
    'cost_calculation' => '0',
    'insufficient_stock' => '0',
    'db_path' => 'db',
    'db_part' => '20971520',
    'db_compress' => '1',
    'db_level' => '9',
    'custom' =>
        array (
        ),
);